"""Report generation for mystery shopping sessions."""

from ..models import MysteryShopSession, TestStatus


def generate_text_report(session: MysteryShopSession) -> str:
    """Generate a plain text scorecard report."""
    lines = []
    lines.append("=" * 60)
    lines.append("🕵️  AI MYSTERY SHOPPER — SCORECARD REPORT")
    lines.append("=" * 60)
    lines.append("")
    lines.append(f"📍 Target:    {session.target.name}")
    lines.append(f"🏷  Industry:  {session.target.industry}")
    lines.append(f"📅 Date:      {session.created_at.strftime('%Y-%m-%d %H:%M')}")
    lines.append(f"🎭 Scenario:  {session.scenario_name}")
    lines.append("")

    # Overall score with visual bar
    score = session.overall_score
    bar = _score_bar(score)
    grade = _score_grade(score)
    lines.append(f"📊 OVERALL SCORE: {score}/100 {grade}")
    lines.append(f"   {bar}")
    lines.append("")

    # Channel results
    for channel_name, result in session.results.items():
        lines.append("-" * 60)
        channel_icon = {"email": "📧", "phone": "📞", "webchat": "💬"}.get(channel_name, "📋")
        lines.append(f"{channel_icon} {channel_name.upper()} CHANNEL")
        lines.append("-" * 60)

        if result.status != TestStatus.COMPLETED:
            lines.append(f"   Status: {result.status.value}")
            lines.append("")
            continue

        lines.append(f"   Score: {result.overall_score}/100 {_score_grade(result.overall_score)}")
        if result.response_time_seconds:
            hours = result.response_time_seconds / 3600
            if hours >= 1:
                lines.append(f"   Response Time: {hours:.1f} hours")
            else:
                minutes = result.response_time_seconds / 60
                lines.append(f"   Response Time: {minutes:.0f} minutes")
        lines.append("")

        # Individual scores
        lines.append("   Detailed Scores:")
        for s in result.scores:
            status = "✅" if s.passed else "❌"
            lines.append(f"   {status} {s.criterion}: {s.score}/100")
            if s.notes:
                lines.append(f"      └─ {s.notes}")
        lines.append("")

        # Summary
        if result.summary:
            lines.append(f"   📝 Summary: {result.summary}")
            lines.append("")

        # Strengths
        if result.strengths:
            lines.append("   💪 Strengths:")
            for s in result.strengths:
                lines.append(f"      • {s}")
            lines.append("")

        # Improvements
        if result.improvements:
            lines.append("   🔧 Areas for Improvement:")
            for imp in result.improvements:
                lines.append(f"      • {imp}")
            lines.append("")

    lines.append("=" * 60)
    lines.append("Generated by AI Mystery Shopper")
    lines.append("=" * 60)

    return "\n".join(lines)


def generate_html_report(session: MysteryShopSession) -> str:
    """Generate an HTML scorecard report."""
    score = session.overall_score
    score_color = _score_color(score)

    channels_html = ""
    for channel_name, result in session.results.items():
        channel_icon = {"email": "📧", "phone": "📞", "webchat": "💬"}.get(channel_name, "📋")

        if result.status != TestStatus.COMPLETED:
            channels_html += f"""
            <div class="channel-card">
                <h3>{channel_icon} {channel_name.upper()}</h3>
                <p class="status">Status: {result.status.value}</p>
            </div>"""
            continue

        scores_html = ""
        for s in result.scores:
            s_color = _score_color(s.score)
            scores_html += f"""
                <div class="score-row">
                    <span class="criterion">{'✅' if s.passed else '❌'} {s.criterion}</span>
                    <span class="score" style="color: {s_color}">{s.score}/100</span>
                    <div class="score-bar-bg"><div class="score-bar-fill" style="width: {s.score}%; background: {s_color}"></div></div>
                    {f'<span class="notes">{s.notes}</span>' if s.notes else ''}
                </div>"""

        response_time_html = ""
        if result.response_time_seconds:
            hours = result.response_time_seconds / 3600
            if hours >= 1:
                response_time_html = f'<p class="response-time">⏱ Response Time: {hours:.1f} hours</p>'
            else:
                response_time_html = f'<p class="response-time">⏱ Response Time: {result.response_time_seconds/60:.0f} minutes</p>'

        strengths_html = "".join(f"<li>{s}</li>" for s in result.strengths)
        improvements_html = "".join(f"<li>{i}</li>" for i in result.improvements)

        ch_color = _score_color(result.overall_score)
        channels_html += f"""
        <div class="channel-card">
            <div class="channel-header">
                <h3>{channel_icon} {channel_name.upper()}</h3>
                <div class="channel-score" style="background: {ch_color}">{result.overall_score}</div>
            </div>
            {response_time_html}
            <p class="summary">{result.summary}</p>
            <div class="scores-list">{scores_html}</div>
            {'<div class="section"><h4>💪 Strengths</h4><ul>' + strengths_html + '</ul></div>' if strengths_html else ''}
            {'<div class="section"><h4>🔧 Improvements Needed</h4><ul>' + improvements_html + '</ul></div>' if improvements_html else ''}
        </div>"""

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mystery Shopping Report — {session.target.name}</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #0f172a; color: #e2e8f0; padding: 2rem; }}
        .container {{ max-width: 800px; margin: 0 auto; }}
        .header {{ text-align: center; margin-bottom: 2rem; }}
        .header h1 {{ font-size: 1.5rem; color: #94a3b8; margin-bottom: 0.5rem; }}
        .header h2 {{ font-size: 2rem; color: #f8fafc; }}
        .header .date {{ color: #64748b; margin-top: 0.5rem; }}
        .overall-score {{ text-align: center; margin: 2rem 0; }}
        .score-circle {{ display: inline-flex; align-items: center; justify-content: center; width: 120px; height: 120px; border-radius: 50%; font-size: 3rem; font-weight: bold; color: white; background: {score_color}; box-shadow: 0 0 30px {score_color}40; }}
        .score-label {{ margin-top: 0.5rem; color: #94a3b8; }}
        .channel-card {{ background: #1e293b; border-radius: 12px; padding: 1.5rem; margin-bottom: 1.5rem; }}
        .channel-header {{ display: flex; justify-content: space-between; align-items: center; margin-bottom: 1rem; }}
        .channel-header h3 {{ font-size: 1.2rem; }}
        .channel-score {{ width: 50px; height: 50px; border-radius: 50%; display: flex; align-items: center; justify-content: center; color: white; font-weight: bold; font-size: 1.1rem; }}
        .response-time {{ color: #94a3b8; margin-bottom: 0.5rem; }}
        .summary {{ color: #cbd5e1; margin-bottom: 1rem; line-height: 1.5; }}
        .score-row {{ margin-bottom: 0.75rem; }}
        .criterion {{ display: block; margin-bottom: 0.25rem; }}
        .score {{ font-weight: bold; }}
        .score-bar-bg {{ height: 6px; background: #334155; border-radius: 3px; margin: 0.25rem 0; }}
        .score-bar-fill {{ height: 100%; border-radius: 3px; transition: width 0.5s; }}
        .notes {{ font-size: 0.85rem; color: #94a3b8; display: block; margin-top: 0.15rem; }}
        .section {{ margin-top: 1rem; }}
        .section h4 {{ margin-bottom: 0.5rem; }}
        .section ul {{ padding-left: 1.5rem; }}
        .section li {{ margin-bottom: 0.3rem; color: #cbd5e1; }}
        .footer {{ text-align: center; color: #475569; margin-top: 2rem; font-size: 0.9rem; }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🕵️ AI Mystery Shopper Report</h1>
            <h2>{session.target.name}</h2>
            <p class="date">{session.created_at.strftime('%B %d, %Y at %H:%M')}</p>
        </div>

        <div class="overall-score">
            <div class="score-circle">{score}</div>
            <p class="score-label">Overall Score</p>
        </div>

        {channels_html}

        <div class="footer">
            <p>Generated by AI Mystery Shopper · Confidential</p>
        </div>
    </div>
</body>
</html>"""


def _score_bar(score: int) -> str:
    filled = score // 5
    empty = 20 - filled
    return f"[{'█' * filled}{'░' * empty}]"


def _score_grade(score: int) -> str:
    if score >= 90: return "⭐ Excellent"
    if score >= 75: return "👍 Good"
    if score >= 60: return "⚠️ Average"
    if score >= 40: return "👎 Below Average"
    return "🚨 Poor"


def _score_color(score: int) -> str:
    if score >= 80: return "#22c55e"
    if score >= 60: return "#eab308"
    if score >= 40: return "#f97316"
    return "#ef4444"
